spring:
  neo4j:
    pool:
      idle-time-before-connection-test: true
  password: qwertyuiopasdfghjklzxcvbnm123457

test:
  password: 123456

test1:
  password: qwertyuiopasdfghjklzxcvbnm123456qwertyuiopasdfghjklzxcvbnm123456qwertyuiopasdfghjklzxcvbnm123456
